### ISSUE TITLE
Installer not working

### ISSUE THREAD

**Issue by baum-usgs** [usgs/groundfailure#194]
I cloned the repository and tried running the installer.  It did not work with an older version of Anaconda.  I installed the latest version of Anaconda and it still did not work correctly.  I followed instructions for making pip and conda work with USGS security measures and still could not make the installer run correctly.  Transcripts of the installer sessions and error messages have been sent to the code developers (Allstadt, Hearn, Thompson) via email.

Besides fixing the installer, it would be helpful to add a document about troubleshooting the installer.

**Comment by kallstadt-usgs** [comment]
May have something to do with the path to conda.sh not being added to active shell

**Comment by kallstadt-usgs** [comment]
Miniconda has to be installed independently and there is a specific line that needs to be added to the .bash_profile. This is now documented in the README.md
