### ISSUE TITLE
Write all model extents in info.json

### ISSUE THREAD

**Issue by mhearne-usgs** [usgs/groundfailure#320]
As seen here: 

https://earthquake.usgs.gov/realtime/product/ground-failure/6000c6mu/us/1602317079636/info.json

Some of the model extents are string references to other JSON files, which are not transferred to PDL.

**Comment by kallstadt-usgs** [comment]
Thanks, I looked into this and it's only true for the alternative models. We just need to update all the codes to reflect the change we made to the two preferred models.
