### ISSUE TITLE
Bug: Callgf is not checking the ShakeMap source

### ISSUE THREAD

**Issue by hschovanec-usgs** [usgs/groundfailure#341]
## Context

Currently Pager only runs when the [type is 'losspager' ](https://github.com/usgs/groundfailure/blob/master/bin/callgf#L1378). As a result the arguments parsed have no direct ShakeMap information.

## Issue 

The whitelist check and the authoritative source check do not work as intended.
**Issue 1.** The source checked against the whitelist is the preferred *event* source, not the ShakeMap source (as the code/logging implies [HERE](https://github.com/usgs/groundfailure/blob/master/bin/callgf#L835-L846)).
**Issue 2.** Line 871 in the authoritative check ([HERE](https://github.com/usgs/groundfailure/blob/master/bin/callgf#L854-L883)), does not compare the ShakeMap source to the authoritative source.

## Proposed solution
**Solution(s) to Issue 1.** 

- Add a code before line [835](https://github.com/usgs/groundfailure/blob/master/bin/callgf#L835) to get the ShakeMap source from the grid.xml

```
shakemap_dict = hdrtuple[0]
shakemap_source = shakemap_dict['shakemap_originator']
````
or from the libcomcat DetailEvent class that was defined on line 719
```
shakemap_product = detail.getProducts('shakemap', source=args.shakesource,  version=args.version)[0]
shakemap_source = shakemap_product.source
``` 

- Update line 835 to compare the ShakeMap source to the whitelist:
```
    if shakemap_source  not in WHITELIST:
```
**Solution to Issue 2.** 
- Update line [871](https://github.com/usgs/groundfailure/blob/master/bin/callgf#L871) to check if the ShakeMap source is authoritative:

```
    is_authoritative = authsrc.lower() == shakemap_source 
```

**Comment by kallstadt-usgs** [comment]
This section of code was a remnant from when we used to trigger off of ShakeMap and is no longer needed because we now trigger of of PAGER and then download either the preferred ShakeMap or a ShakeMap from the specified source so this authoritativeness check is not needed. Resolved by pull request #345
