### ISSUE TITLE
f-string issue in notes

### ISSUE THREAD

**Issue by hschovanec-usgs** [usgs/groundfailure#358]
https://github.com/usgs/groundfailure/blob/03afe7bb2dab01a3a4a2b257a6c5a4c8393bb368/gfail/models/jessee_2018.py#L84

This model has a malformed f-string: so note shows "from {OLD_UNCONSOLIDATED} to better" rather than the value.

**Comment by SamirPS** [comment]
You want to correct the issue or i can take it ?

**Comment by emthompson-usgs** [comment]
Closed by #360.
