### ISSUE TITLE
Make groundfailure trigger by pdl instead of crontab searching every 5 mins

### ISSUE THREAD

**Issue by kallstadt-usgs** [usgs/groundfailure#92]

**Comment by mhearne-usgs** [comment]
@kallstadt Do you have triggering criteria, like:
 - minimum magnitude?
 - Shakemap originator is/ is not authoritative for this region (PAGER does this)
 - others?

**Comment by kallstadt-usgs** [comment]
Yes, current triggering criteria (subject to change) are: 
[THRESHOLDS]
eis = yellow
mag = 6.5
mmi = 7

See autogf.py for how it currently runs

**Comment by kallstadt-usgs** [comment]
autogf.py is located in the gfail home directory  on the loss machine, btw.
